# Generated by Django 3.2.4 on 2021-07-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recorridos',
            options={'ordering': ['-created'], 'verbose_name': 'Recorrido', 'verbose_name_plural': 'Recorridos'},
        ),
    ]
