# Generated by Django 3.2.4 on 2021-08-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_mensajecontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='registroRecorrido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Usuario(s)')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('recorrido', models.TextField(verbose_name='Nombre del recorrido')),
                ('telefono', models.TextField(verbose_name='Número de teléfono')),
                ('nPersonas', models.TextField(verbose_name='Participantes del recorrido')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['-created'],
            },
        ),
    ]
