# Generated by Django 3.2.4 on 2021-08-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_recorridos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorridos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
